"""Safe THUFootball integration package."""

from .client import THUFootballClient
from .errors import (
    AuthenticationError,
    BatchQueryError,
    ConfigurationError,
    DataConflict,
    InvalidResponse,
    PermissionError,
    QueryValidationError,
    RateLimited,
    ReportValidationError,
    SchemaError,
    THUFootballError,
    Timeout,
)
from .models import (
    GameDetail,
    GameEvent,
    GameEventIssue,
    GameQuery,
    GameReportFile,
    GameStatus,
    GameSummary,
    HeadToHeadHistory,
    HeadToHeadSummary,
    MatchResult,
    PreparedGameReport,
    RefereeAssignment,
    ReportSettings,
    TeamGameResult,
    TeamTournamentOutcome,
    TournamentRef,
    TournamentSnapshot,
    UserProbe,
)
from .policy import BLACKLISTED_TOURNAMENT_IDS
from .queries import THUFootballQueryService
from .reports import (
    THUFootballReportService,
    prepare_game_report,
    render_game_report,
    resolve_report_team_name,
)

__all__ = [
    "AuthenticationError",
    "BLACKLISTED_TOURNAMENT_IDS",
    "BatchQueryError",
    "ConfigurationError",
    "DataConflict",
    "GameDetail",
    "GameEvent",
    "GameEventIssue",
    "GameQuery",
    "GameReportFile",
    "GameStatus",
    "GameSummary",
    "HeadToHeadHistory",
    "HeadToHeadSummary",
    "InvalidResponse",
    "MatchResult",
    "PermissionError",
    "PreparedGameReport",
    "QueryValidationError",
    "RateLimited",
    "RefereeAssignment",
    "ReportSettings",
    "ReportValidationError",
    "SchemaError",
    "THUFootballClient",
    "THUFootballError",
    "THUFootballQueryService",
    "THUFootballReportService",
    "TeamGameResult",
    "TeamTournamentOutcome",
    "Timeout",
    "TournamentRef",
    "TournamentSnapshot",
    "UserProbe",
    "render_game_report",
    "prepare_game_report",
    "resolve_report_team_name",
]
