"""Safe THUFootball integration package."""

from .client import THUFootballClient
from .errors import (
    AuthenticationError,
    BatchQueryError,
    ConfigurationError,
    DataConflict,
    InvalidResponse,
    PermissionError,
    QueryValidationError,
    RateLimited,
    SchemaError,
    THUFootballError,
    Timeout,
)
from .models import (
    GameDetail,
    GameEvent,
    GameQuery,
    GameReportFile,
    GameStatus,
    GameSummary,
    HeadToHeadHistory,
    HeadToHeadSummary,
    MatchResult,
    RefereeAssignment,
    ReportSettings,
    TeamGameResult,
    TeamTournamentOutcome,
    TournamentRef,
    TournamentSnapshot,
    TournamentTeam,
    UserProbe,
)
from .policy import BLACKLISTED_TOURNAMENT_IDS
from .queries import THUFootballQueryService
from .reports import THUFootballReportService, render_game_report

__all__ = [
    "AuthenticationError",
    "BLACKLISTED_TOURNAMENT_IDS",
    "BatchQueryError",
    "ConfigurationError",
    "DataConflict",
    "GameDetail",
    "GameEvent",
    "GameQuery",
    "GameReportFile",
    "GameStatus",
    "GameSummary",
    "HeadToHeadHistory",
    "HeadToHeadSummary",
    "InvalidResponse",
    "MatchResult",
    "PermissionError",
    "QueryValidationError",
    "RateLimited",
    "RefereeAssignment",
    "ReportSettings",
    "SchemaError",
    "THUFootballClient",
    "THUFootballError",
    "THUFootballQueryService",
    "THUFootballReportService",
    "TeamGameResult",
    "TeamTournamentOutcome",
    "Timeout",
    "TournamentRef",
    "TournamentSnapshot",
    "TournamentTeam",
    "UserProbe",
    "render_game_report",
]
